# Generated by Django 4.1.5 on 2023-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_availabe_book_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Order Amount'),
        ),
    ]
