# Generated by Django 4.1.5 on 2023-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_available',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Number of Available Books'),
        ),
    ]
