# Generated by Django 4.1.5 on 2023-01-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_book_num_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book',
            new_name='books',
        ),
    ]
