# Generated by Django 4.1.5 on 2023-01-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_book_order_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books',
            new_name='book',
        ),
    ]
