# Generated by Django 4.1.6 on 2023-02-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_mfginventory_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_available',
            new_name='quantity',
        ),
    ]
