# Generated by Django 4.1.6 on 2023-02-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
