# Generated by Django 4.1.6 on 2023-02-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfginventory',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Book ID'),
        ),
    ]
