# Generated by Django 4.1.5 on 2023-01-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_orders_rename_book_books_rename_user_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='books',
        ),
        migrations.AddField(
            model_name='orders',
            name='books',
            field=models.ManyToManyField(blank=True, to='website.books'),
        ),
    ]
